### ISSUE TITLE
Comunication aborted for dropped messages

### ISSUE THREAD

**Issue by FrancescoRuscelli** [ADVRHumanoids/XBotControl#30]
Sending commands to the robot after having changed the robot control mode back and forth (i.e. from Position to Stiffness to Position again) aborts the communication with the error: "Detected X dropped messages for joint ...". @alaurenzi

**Comment by alaurenzi** [comment]
The bug is due to the xbotcore seeing a "hole" in the sequence identifier for the impedance fields of the control message. It is indeed a bug, because users are unable to change control mode during runtime. I'll think to a solution. Meanwhile you can comment the relevant lines on XBotNRTRef plugin so as to disable the check. @liesrock

**Comment by liesrock** [comment]
Should be solved by @alaurenzi in xbot2.
